### ISSUE TITLE
Can't run Docker across FUSE mount

### ISSUE THREAD

**Issue by a-frantz** [dnanexus/dxfuse#53]
I tried mounting a project so I could run a Docker container using it interactively, but Docker couldn't mount a volume across the `dxfuse` mount. I was able to work around it without using `dxfuse`, but it would be a great feature to support.

**Comment by kpjensen** [comment]
This should work with some configuration tweaks. I tested the following on Ubuntu 16.04. 

Uncomment the `user_allow_other` line in `/etc/fuse.conf`. Here is my conf file. 
```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

Invoke `dxfuse` as sudo before running the Docker container.
```
sudo ./dxfuse mountpoint project-id
```
Now bind-mounting the directory should work without permission denials.
```
sudo docker run --mount src=/mountpoint,target=/dnaxproject,type=bind busybox ls /project
```

Let me know if this works for you,

Kurt
