### ISSUE TITLE
processing .bgen file yields corruption over dxfuse but not locally

### ISSUE THREAD

**Issue by carbocation** [dnanexus/dxfuse#83]
The UK Biobank imputed files are large (hundreds of gigabytes) and I am trying to select 10 variants from one file over a `dxfuse` mount. On GCP, I use `gcsfuse` for this purpose, and it works very well. On the DNANexus platform using `dxfuse`, I cannot fetch the data I need without corruption.

I have done a binary search through the original list of 10,000 SNPs to narrow this down to the smallest reproducible set, and I can now reliably trigger the creation of corrupted output over `dxfuse` with a list of just 10 SNPs.

I believe that this is a `dxfuse` problem because when I download the 101GB source file and run the same code, the output data are fine / uncorrupted. However, I don't consider that a reasonable mitigation strategy, because it comes at a 1,000-fold cost increase.

With that as background, I am starting here because I want to see if there is anything in my `dxfuse` mounting strategy that could be contributing to this problem. The strategy is:

```sh
mkdir -p /mnt/tmp
dxfuse -verbose 2 /mnt/tmp "${DX_PROJECT_CONTEXT_ID}"
```

**Comment by emiloslavsky** [comment]
mount incantation looks correct, @kpjensen please confirm.

**Comment by emiloslavsky** [comment]
@carbocation please provide a reproduction test case, and the version of dxfuse that has the problem you are reporting.

**Comment by carbocation** [comment]
Test cases (both passing and failing) were provided by email to DNANexus on May 8, 2023.

**Comment by emiloslavsky** [comment]
Thank you!  Support was able to repro the pass and fail runs.

**Comment by kpjensen** [comment]
This bug should be addressed in the latest release https://github.com/dnanexus/dxfuse/releases/tag/v1.4.0.
